Add support for manually launching a publication with tag validation in GitHub Actions

diff --git a/.github/workflows/publish_jsr.yml b/.github/workflows/publish_jsr.yml
--- a/.github/workflows/publish_jsr.yml
+++ b/.github/workflows/publish_jsr.yml
@@ -5,10 +5,11 @@ on:
             - Run Deno Tests
         types:
             - completed
+    workflow_dispatch:
 
 jobs:
     publish:
-        if: ${{ github.event.workflow_run.conclusion == 'success' }}
+        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
         runs-on: ubuntu-latest
 
         permissions:
@@ -17,6 +18,19 @@ jobs:
 
         steps:
             - uses: actions/checkout@v4
+
+            - name: Check tag
+              if: ${{ github.event_name == 'workflow_dispatch' }}
+              id: version
+              run: |
+                  VERSION=$(jq -r '.version' deno.json)
+                  echo "Version: $VERSION"
+                  if [[ "$VERSION" == *-* ]]; then
+                    echo "Tag found, manual publishing allowed"
+                  else
+                    echo "Error: Manual publishing without a tag is not allowed" >&2
+                    exit 1
+                  fi
 
             - name: Publish package
               run: npx jsr publish
